// import 'package:jaspr/html.dart';
import 'package:jaspr/server.dart';
import 'package:jaspr_portfolio/theme/styles.dart';
import './app.dart';

void main() {
  runApp(
    Document(
      title: 'Portfolio Web',
      charset: 'UTF-8',
      viewport: 'width=device-width, initial-scale=1.0',
      head: [
        // Link the styles.css file, this will be generated by the tailwind integration.
        // link(href: 'css/styles.css', rel: 'stylesheet'),
      ],
      styles: styles,
      body: App(),
    ),
  );
}
